### PR TITLE
Enalbe fast creation of virtual environments with pip-tools

### PR DESCRIPTION
**Pull request by jruizaranguren**
I have added a minimum setup that facilitates the creation and update of a virtual environment for bark project. I have tried to keep it as simple as possible:

* it only adds `pip-tools` for virtual environment management.
* I have added a Makefile with commands to perform a fast setup of the project with `make setup` and also for updating virtual envioronments in case they evolve with time.

### CODE REVIEW

**Comment by tongbaojia** [comment]
Hi @jruizaranguren, thanks for the PR. 

The PR is very specific to the Python version, env of choice though. There are files that are generated with Python version 3.11 but I'd imagine there are users with 3.10, 12 etc. It would be great to keep the main repo generalizable across different development envs. I'd recommend making some changes in this PR that remove the auto-generated files.

**Comment by jruizaranguren** [comment]
@tongbaojia you are right. I wanted to make it as simple as possible, but requiring a specific python version is a hard constraint.
I see two alternatives:

* remove requirements.txt, dev-requirements.txt from source control and take python version from environment. It assumes that each user will fork the repository, will invoke `make setup` and they will upload their *.txt files to their branch for convenience.
* add tox to the mix, so we can effectively manage different environments. I doubt is worth the effort.
What do you think?

**Comment by tongbaojia** [comment]
@jruizaranguren My 2 cents: I think a flexible package should support multiple envs/developers. The less constraint there is, the easier different users could interact with it. 

For example, consider pandas, you don't want all pandas to have a vital requirement on dependencies -- different versions of pandas may require a min version of numpy and that's fine, but requiring a requirement file with fixed versions of dependencies is too much (this will cause headaches for developers to resolve dependency issues in python).  Creating virtual envs & pip tool management, should not be the user/engineer's job and done on the backend, rather than a pip-installable pkg.  

So I don't think that this diff needs to be landed into the main repo. You should instead maintain all these requirement.txt etc in your dev project that uses bark. That would be an optimal solution.

**Comment by jruizaranguren** [comment]
Agree. Closing pull request.

**Pull request closed without merging**
