### PR TITLE
Fixes MPS device errors from Tensor.type() when using generate_text_semantic and generate_coarse

### PR DESCRIPTION
**Pull request by fiq**
Addresses MPS specific errors in `generate_text_semantic` and `generate_coarse` when calling Tensor.type for logit handling on MPS devices. See this underlying pytorch issue https://github.com/pytorch/pytorch/issues/78929

**FIX Tested On:**
M2Pro

**Expected**:
* Seamless voice generation

**Actual**:

```
❯ SUNO_ENABLE_MPS=True python ./test-case.py
  0%|                                                                                                                                                                                                                                                           	| 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/innovation/Code/bark/./test-case.py", line 57, in <module>
	audio_array=  say_semantic(training_text, voice_name)
  File "/Users/innovation/Code/bark/./test-case.py", line 30, in say_semantic
	x_semantic = generate_text_semantic(
  File "/Users/innovation/Code/bark/bark/generation.py", line 479, in generate_text_semantic
	relevant_logits = relevant_logits.to(logits_device).type(logits_dtype)
ValueError: invalid type: 'torch.mps.FloatTensor'
  0%|
```

**To recreate:** 

To recreate prior to this PR, on an MPS device (tested on M2Pro), use this test script:
``` lang=python
from bark.generation import load_codec_model, generate_text_semantic
from bark.generation import SAMPLE_RATE, preload_models, codec_decode, generate_coarse, generate_fine, generate_text_semantic
from bark.api import generate_audio
import numpy as np
from scipy.io.wavfile import write as write_wav
import sounddevice as sd
import pprint
pp = pprint.PrettyPrinter()
preload_models()

def say_semantic(text_prompt, voice_name):
  preload_models(
    text_use_gpu=True,
    text_use_small=False,
    coarse_use_gpu=True,
    coarse_use_small=False,
    fine_use_gpu=True,
    fine_use_small=False,
    codec_use_gpu=True,
    force_reload=True,
  )


  x_semantic = generate_text_semantic(
        text_prompt,
        history_prompt=voice_name,
        temp=0.7,
        top_k=50,
        top_p=0.95,
    )

  x_coarse_gen = generate_coarse(
        x_semantic,
        history_prompt=voice_name,
        temp=0.7,
        top_k=50,
        top_p=0.95,
    )

  x_fine_gen = generate_fine(
    x_coarse_gen,
    history_prompt=voice_name,
    temp=0.5,
    )

  return codec_decode(x_fine_gen)

voice_name="en_speaker_0"
training_text = "Hello, there!"
audio_array=  say_semantic(training_text, voice_name)

pp.pprint(audio_array)
write_wav("output.wav", SAMPLE_RATE, audio_array)
sd.play(audio_array, SAMPLE_RATE)
# allow async sd.play to complete
sd.wait()

```

Btw, I'm LOVING bark. Thanks for OSS'ing it!

### CODE REVIEW

**Comment by gkucsko** [comment]
Awesome thanks! Can't this PR be simplified a lot by changing just the dtype issue? the shuttling is already a no-op if we don't have MPS right? so we only have to make sure that in the MPS case it doesn't error out. as for that, why does it actually? seems super weird that you can set and mps tensor to an mps dtype.. any thoughts?

**Comment by fiq** [comment]
Thanks! I've pushed up a simplification which has been tested for both 'cpu' and 'mps' devices. You'll need to test it on CUDA as my nvidia is somewhat dated.

> Awesome thanks! Can't this PR be simplified a lot by changing just the dtype issue? the shuttling is already a no-op if we don't have MPS right? 

That's right. A quick disclaimer that I'm new to pytorch internals here.  The issue appears to be that the original line`relevant_logits.to(logits_device).type(logits_dtype)` bailed with `ValueError: invalid type: 'torch.mps.FloatTensor'` 

> so we only have to make sure that in the MPS case it doesn't error out. as for that, why does it actually? 

This was down to lacking support for MPS (at this time) in `.type()` (and also a possible upcoming deprecation of .type() - see the issue I referenced above)

Having looked at the pytorch source and the exception being raised by pytorch, **I'm about 90% sure this is an issue with `.type()` not supporting MPS in a per-device conditional flow it has** 

My current tested 'fix' is effectively a rewrite of the `relevant_logits.to(device).type(type)` The previous change had only added an exception for MPS (apologies the previous set of this PR would have broken it for other device types - as I had only tested against MPS!)

The change which I have _now_ PUSHED should work on all devices. It delegates dtype restoration, after the numpy mashelling, back to Tensor.to(device) I'm not specifying the original target dtype anymore, which I think is better. As I've only tested this on CPU and MPS, it would be appreciated if you'd validate against a cuda. 

Would be super grateful if we can get this in as it will fix Bark for other MPS users (without adding a kludgy CPU fall back). Thank you!

**Comment by gkucsko** [comment]
sounds great thanks, can you please also remove the now unused variables `logits_device` and `logits_dtype` in both places. we don't need them anymore, right?

**Comment by fiq** [comment]
We can only drop `logits_dtype` and not `logits_device` (although I've renamed this to be more meaningful) is this used as a transient variable to hold the device type to adapt the tensor to later.
 
Pushing up a change with just logits_dtype removed. As *we mutate relevant_logits to a numpy tensor and back, we'd still need a temporary variable to hold the device type*; before to marshalling to numpy and then back. I caught this in testing and got a later error of `RuntimeError: torch.cat(): all input tensors must be on the same device. Received mps:0 and cpu` which makes sense on re-inspection.

**Comment by fiq** [comment]
I've pushed up the simplifications from my fork. It's now down to just a few lines. `logits_device` is renamed to `original_logits` to better express its purpose. Thanks.

**Comment by gkucsko** [comment]
awesome thanks, wait so all that was buggy was the typecast before? cool
sorry to be nitpicky but can you leave the empty lines that are unlrelated to the commit? Thaaaank you!

**Comment by fiq** [comment]
💯 My introduced newlines have been removed and the retracted newlines have been re-introduced. 

Cheers. 

> awesome thanks, wait so all that was buggy was the typecast before? cool

Correct. It started with observing that `.type()` for an MPS tensor was not supported, however, effectively this came down to its use for type casting. Apologies for the latency. This is fun-ware whenever I sneak in some time.

**Comment by fiq** [comment]
I've rebased and squashed the last few commits, force pushing slightly cleaner history to this PR. Should make for less noise on a merge.

**Comment by gkucsko** [comment]
thanks a bunch!

**Pull request merged**
