### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by SleepTheGod**
pip install -r requirements.txt

The requirements.txt file should contain as followed
torch==1.12.0+cpu
torchvision==0.13.0+cpu
torchaudio==0.12.0+cpu
transformers==4.20.1
bark==0.1.0

### CODE REVIEW

**Comment by 336699lll** [comment]
啊飒飒飒飒

**Review by barnett-yuxiang — COMMENTED** [review]
Specifying a version range for dependent packages instead of a fixed version can improve package compatibility and reduce the risk of dependency conflicts.

**Comment by barnett-yuxiang** [comment]
Add comments : Add comments to each dependency package, explaining why the project needs this package, especially those less common or specific dependencies. This can help team members understand the purpose of each library, for example:

```
torch==1.12.0+cpu  # PyTorch framework for CPU-only version
transformers==4.20.1  # Library for state-of-the-art natural language processing
bark==0.1.0  # Hypothetical library for audio processing, version 0.1.0
```

**Comment by rsxdalv** [comment]
Dependencies are defined here:
https://github.com/suno-ai/bark/blob/main/pyproject.toml#L17C1-L28C2

```
dependencies = [
    "boto3",
    "encodec",
    "funcy",
    "huggingface-hub>=0.14.1",
    "numpy",
    "scipy",
    "tokenizers",
    "torch",
    "tqdm",
    "transformers",
]
```

Bark works with far more versions than listed here.

And specifying bark as a dependency of bark is invalid.

**Pull request closed without merging**
