### PR TITLE
Boilerplate MPS code

### PR DESCRIPTION
**Pull request by huksley**
Adds get_device() and renames _clear_cuda_cache to _clear_device_cache.
This does not give Apple Silicon support yet but makes it easier to implement in the future.
Uses CUDA if available first.

Run as `PYTORCH_ENABLE_MPS_FALLBACK=1 python 1.py`

```
text_prompt = """
    WOMAN: I would like an oat milk latte please.
    MAN: Wow, that's expensive!
"""
audio_array = generate_audio(text_prompt)
```

Takes around 15 mins on M2 Pro with 32Gb and generates some noise or I just write WAV file in a wrong way :)

FIXME: `aten::_weight_norm_interface` are not currently implemented in MPS as tracked in:

https://github.com/pytorch/pytorch/issues/77764#issuecomment-1516967265

### CODE REVIEW

**Comment by gkucsko** [comment]
haha awesome thanks. not much experience here, would love for someone to test and verify

**Review by sevdari — APPROVED** [review]

**Comment by huksley** [comment]
cleaned up and rebased on current main branch @gkucsko @sevdari

**Comment by gkucsko** [comment]
fantastic thanks, do we have any benchmarks here just to make sure it actually improves things vs cpu? also, gotta double check it doesn't break anything on gpu, but looks good on quick glance

**Comment by gkucsko** [comment]
hm, i'm getting much faster prediction speeds on CPU..

**Review by bujosa — APPROVED** [review]

**Comment by gkucsko** [comment]
the noise output comes from `torch.multinomial`, somehow that seems bugged under mps and returns somethine that looks like constant numeric overflow

**Comment by olso** [comment]
Anyone else getting this?

```sh
NotImplementedError: The operator 'aten::_weight_norm_interface' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS
```

**Comment by domcross** [comment]
> Anyone else getting this?

Yes. You need to set `PYTORCH_ENABLE_MPS_FALLBACK=1`. Either by `export PYTORCH_ENABLE_MPS_FALLBACK=1` in your console session or prefixing your python-call, e.g. `PYTORCH_ENABLE_MPS_FALLBACK=1 python myscript.py`

**Comment by gkucsko** [comment]
ok just simplified device placement a bit as well as added experimental MPS support (disabled by default via environment variable): https://github.com/suno-ai/bark/commit/6c26fb7b3463334ae9fb4d63dae52f3c29506db0

on M1 max i am seeing:
image

so it kinda looks like the semantic model is better on cpu but coarse benefits from mps. (note that this is on pytorch nightly). some more experiments needed....

**Comment by gkucsko** [comment]
hmm, looks like it's warmup related. running again is faster for both. Alright, considering this experimental MPS support for now which makes inference roughly 2x faster. gonna close this PR for now. MPS can now be enabled via:
```
import os
os.environ["SUNO_ENABLE_MPS"] = "True"
```

**Comment by gkucsko** [comment]
try torch nightly

**Pull request closed without merging**
